---
- hosts: webservers
  become: true
  tasks:
    - name: "Task 1"
      shell: date
      register: the_date
    - debug: msg="{{ the_date.stdout }}"

    - name: "Task 2"
      shell: whoami
      register: user_name
    - debug: msg="{{ user_name.stdout }}"

    - name: "Task 3"
      shell: uname -a
      register: response_uname
    - debug: msg="{{ response_uname.stdout }}"

    - name: "Task 4"
      shell: df -h
      register: process_info
    - debug: msg="{{ process_info.stdout }}"

    - name: "Task 5"
      shell: free -m
      register: free_response
    - debug: msg="{{ free_response.stdout }}"

    - name: "Install epel repository"
      yum:
        name: epel-release
    - name: "Install nginx"
      yum:
        name: nginx
        state: present
    - name: "Start nginx"
      service:
        name: nginx
        state: started
        enabled: yes
    - name: "Declare hostname"
      shell: "echo $HOSTNAME"
      register: print_hostname
    - name: "Configure nginx"
      template:
        src: templates/index.j2
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: wheel
        mode: "0644"
